### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Goldenprevue** [Goldenprevue/pre-onboarding-11th-4#17]
- [x] API 호출 활용 검색어 추천
- [x] 검색어 없을 시 "검색어 없음" 표출
- [x] API 호출별로 로컬 캐싱 구현
- [x] expire-time 구현
- [x] API 호출 횟수를 줄이는 전략 수립 및 실행
- [x] API 호출할 때 마다`console.log("calling api")` 출력하게 만들기
- [x] 키보드만으로 추천 검색어 이동 가능하게 만들기
- [x] README 작성

챌리지
- [x] 사용자가 검색한 키워드 expire-time으로 브라우저 스토리지 이용해서 저장하기
- [x] AWS CI/CD
- [x] Refactor
